### ISSUE TITLE
Could you please provide the name of the article corresponding to the code? Thank you.

### ISSUE THREAD

**Issue by zly336** [avranasa/DRL_Scheduling_Communications#1]

**Comment by avranasa** [comment]
Thank you for comment.   The link to our paper:
  https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=10250919
  
  In case you want to use either the github repository for your research project please use the following citation:
  
@ARTICLE{DRL_Scheduling_Communications ,
  author={Avranas, Apostolos and Ciblat, Philippe and Kountouris, Marios},
  journal={IEEE Transactions on Machine Learning in Communications and Networking}, 
  title={Deep Reinforcement Learning for Resource Constrained Multiclass Scheduling in Wireless Networks}, 
  year={2023},
  volume={1},
  number={},
  pages={225-241},
  doi={10.1109/TMLCN.2023.3314705}}

**Comment by zly336** [comment]
Thank you very much for your reply, thank you.
